### PR TITLE
Use the new insertionPoint option, update jss deps

### PR DESCRIPTION
**Pull request by kof**

### CODE REVIEW

**Comment by kof** [comment]
Locally all tests are passing, maybe the ci has cached the dependencies?

**Comment by kof** [comment]
Oh my fault I used the previous jss version.

**Comment by kof** [comment]
Can't figure out what it is, something is leaking.

**Comment by nathanmarks** [comment]
@kof will merge and then fix

**Comment by kof** [comment]
Nice, it is released! Thanks a lot!

**Pull request merged**
